### ISSUE TITLE
Doesn't work if path doesn't include leading /

### ISSUE THREAD

**Issue by joegoldbeck** [meteorhacks/fast-render#133]
Just spent a while debugging an issue where fastRender wasn't working on a route. Eventually tracked it down to the leading slash in the `path` attribute of a route. If the route is specified with `somepathsegment/anothersegment` the fastRender logic doesn't fire (though iron router treats the route as if it had the leading /), but if it is specified as `/somepathsegment/anothersegment` then it works correctly. It's confusing because iron-router works fine in both situations, and fast-render doesn't complain about the lack of leading slash, it just simply doesn't do it's thing

**Comment by arunoda** [comment]
We need to have a leading slash "/". Otherwise things are unpredictable and we don't add slashes for you.

In flow router we don't allow you to write routes without "/" :) We throw an error. I think we can do the same for fast-render as well. Then someone else don't wanna debug hard as you?

Could you send me a PR where it throws an error, if there is no leading "/" ?

**Comment by joegoldbeck** [comment]
Yup! Opened PR #135
